param([ValidateSet('Orchestrate','Boot','Library')][string]$Mode='Orchestrate',[string]$RunRoot='',[int]$Seed=701,[string]$Core='qwen3.5:4b',[string]$EmbeddingModel='bge-m3')
$ErrorActionPreference='Stop';$scriptRoot=Split-Path -Parent $MyInvocation.MyCommand.Path;$utf8=[Text.UTF8Encoding]::new($false)
function WriteText([string]$p,[string[]]$lines){$d=Split-Path -Parent $p;if($d){$null=New-Item -ItemType Directory -Force -Path $d};[IO.File]::WriteAllLines($p,$lines,$utf8)}
function ReadText([string]$p){[IO.File]::ReadAllText($p,$utf8)}
function Field([string]$text,[string]$name){$m=[regex]::Match($text,'(?m)^'+[regex]::Escape($name)+'=(.+?)\s*$');if($m.Success){$m.Groups[1].Value.Trim()}else{$null}}
function Token([int]$s,[string]$k,[int]$i){$sha=[Security.Cryptography.SHA256]::Create();$h=$sha.ComputeHash([Text.Encoding]::UTF8.GetBytes("$s|$k|$i"));$sha.Dispose();$k.ToUpperInvariant()+'-'+[Convert]::ToHexString($h).Substring(0,10)}
function Core([string]$prompt){$system="Classify retrieval intent only.`nCONTINUITY: combine relationship, past correction, later actual, current work and learning.`nSPEAKER: asks who said a known statement.`nINCOMPLETE: asks whether an uncertain claim with unnamed or missing evidence is definitely true.`nUNKNOWN: only when the request itself has no identifiable subject.`nOutput exactly INTENT=<one label>.";$body=@{model=$Core;system=$system;prompt=$prompt;stream=$false;think=$false;keep_alive='5m';options=@{temperature=0;seed=$Seed;num_ctx=2048;num_predict=32}}|ConvertTo-Json -Depth 6;$sw=[Diagnostics.Stopwatch]::StartNew();$r=Invoke-RestMethod 'http://127.0.0.1:11434/api/generate' -Method Post -ContentType 'application/json' -Body ([Text.Encoding]::UTF8.GetBytes($body)) -TimeoutSec 120;$sw.Stop();[pscustomobject]@{Text=([string]$r.response).Trim();Prompt=[int]$r.prompt_eval_count;Output=[int]$r.eval_count;Ms=$sw.ElapsedMilliseconds}}
function Embed([string[]]$items){$body=@{model=$EmbeddingModel;input=$items;keep_alive='5m'}|ConvertTo-Json -Depth 5;$sw=[Diagnostics.Stopwatch]::StartNew();$r=Invoke-RestMethod 'http://127.0.0.1:11434/api/embed' -Method Post -ContentType 'application/json' -Body ([Text.Encoding]::UTF8.GetBytes($body)) -TimeoutSec 120;$sw.Stop();[pscustomobject]@{Vectors=$r.embeddings;Ms=$sw.ElapsedMilliseconds}}
function Cosine($a,$b){$dot=0.0;$aa=0.0;$bb=0.0;for($i=0;$i-lt$a.Count;$i++){$dot+=$a[$i]*$b[$i];$aa+=$a[$i]*$a[$i];$bb+=$b[$i]*$b[$i]};if($aa-eq0-or$bb-eq0){0}else{$dot/[Math]::Sqrt($aa*$bb)}}
function Parse-Index([string]$text){$list=[Collections.Generic.List[object]]::new();$r=$null;foreach($line in $text-split"`r?`n"){if($line-eq'[NODE]'){$r=[ordered]@{};continue};if($line-eq'[END]'){$list.Add([pscustomobject]$r);$r=$null;continue};if($r-and$line-match'^([^=]+)=(.*)$'){$r[$Matches[1]]=$Matches[2]}};@($list)}
function Add-Node($lines,[hashtable]$n){$lines.Add('[NODE]');foreach($k in @('ID','TYPE','PERSON_ID','RELATION_ID','PROJECT_ID','TIME','STATE','AUTHORITY','SPEAKER_ID','SOURCE_ID','SUMMARY','PATH')){$lines.Add("$k=$($n[$k])")};$lines.Add('[END]')}
function Add-Region($lines,[string]$id,[string]$summary,[string]$path){$lines.Add('[NODE]');$lines.Add("ID=$id");$lines.Add("SUMMARY=$summary");$lines.Add("PATH=$path");$lines.Add('[END]')}
function Read-Node([string]$brain,[string]$id){$path='nodes/by-id/'+$id+'.txt';$full=Join-Path $brain $path;if(-not(Test-Path -LiteralPath $full)){throw 'node_not_found'};$text=ReadText $full;[pscustomobject]@{ID=(Field $text 'ID');TYPE=(Field $text 'TYPE');PERSON_ID=(Field $text 'PERSON_ID');RELATION_ID=(Field $text 'RELATION_ID');PROJECT_ID=(Field $text 'PROJECT_ID');TIME=(Field $text 'TIME');STATE=(Field $text 'STATE');AUTHORITY=(Field $text 'AUTHORITY');SPEAKER_ID=(Field $text 'SPEAKER_ID');SOURCE_ID=(Field $text 'SOURCE_ID');RELATIONSHIP_NODE_ID=(Field $text 'RELATIONSHIP_NODE_ID');CURRENT_NODE_ID=(Field $text 'CURRENT_NODE_ID');LEARNING_NODE_ID=(Field $text 'LEARNING_NODE_ID');SUMMARY=(Field $text 'SUMMARY');PATH=$path;TEXT=$text}}
function Build-Brain([string]$root,[int]$seed){
 $brain=Join-Path $root 'brain';$oracle=Join-Path $root 'oracle';$person=Token $seed 'person' 0;$decoy=Token $seed 'person' 1;$ally=Token $seed 'ally' 0;$project=Token $seed 'project' 0;$relation=Token $seed 'relation' 0;$historical=Token $seed 'event' 0;$actual=Token $seed 'actual' 0;$current=Token $seed 'current' 0;$learning=Token $seed 'learning' 0;$speakerEvent=Token $seed 'event' 1;$incomplete=Token $seed 'event' 2;$unknown=Token $seed 'unknown' 0;$unfinished=Token $seed 'unfinished' 0
 $nodes=[Collections.Generic.List[object]]::new()
 $nodes.Add(@{ID=$person;TYPE='PERSON';PERSON_ID=$person;RELATION_ID='NONE';PROJECT_ID=$project;TIME='2026-01-01';STATE='CURRENT';AUTHORITY='VERIFIED';SPEAKER_ID=$person;SOURCE_ID='SRC-PERSON';SUMMARY='quiet archive steward maintaining local continuity with a trusted collaborator';PATH='nodes/person-main.txt'})
 $nodes.Add(@{ID=$decoy;TYPE='PERSON';PERSON_ID=$decoy;RELATION_ID='NONE';PROJECT_ID='DECOY-PROJECT';TIME='2026-01-02';STATE='CURRENT';AUTHORITY='VERIFIED';SPEAKER_ID=$decoy;SOURCE_ID='SRC-DECOY';SUMMARY='quiet archive engineer maintaining continuity with a trusted collaborator';PATH='nodes/person-decoy.txt'})
 $nodes.Add(@{ID=$relation;TYPE='RELATIONSHIP';PERSON_ID=$person;RELATION_ID=$relation;PROJECT_ID=$project;TIME='2026-02-01';STATE='CURRENT';AUTHORITY='VERIFIED';SPEAKER_ID=$person;SOURCE_ID='SRC-REL';SUMMARY='archive steward and primary collaborator verify corrections together without treating either speaker as infallible';PATH='nodes/relation-main.txt'})
 $nodes.Add(@{ID=(Token $seed 'relation' 1);TYPE='RELATIONSHIP';PERSON_ID=$decoy;RELATION_ID=(Token $seed 'relation' 1);PROJECT_ID='DECOY-PROJECT';TIME='2026-02-02';STATE='CURRENT';AUTHORITY='VERIFIED';SPEAKER_ID=$decoy;SOURCE_ID='SRC-REL-X';SUMMARY='archive engineer and primary collaborator verify corrections together without treating either speaker as infallible';PATH='nodes/relation-decoy.txt'})
 $nodes.Add(@{ID=$historical;TYPE='EVENT';PERSON_ID=$person;RELATION_ID=$relation;PROJECT_ID=$project;TIME='2026-03-01';STATE='HISTORICAL';AUTHORITY='VERIFIED';SPEAKER_ID=$ally;SOURCE_ID='SRC-EVENT-H';SUMMARY='earlier workshop conversation misattributed a calibration remark to the archive steward';PATH='nodes/event-historical.txt'})
 $nodes.Add(@{ID=$actual;TYPE='ACTUAL';PERSON_ID=$person;RELATION_ID=$relation;PROJECT_ID=$project;TIME='2026-03-02';STATE='ACTUAL';AUTHORITY='VERIFIED';SPEAKER_ID=$ally;SOURCE_ID=$historical;SUMMARY='later source review proved the collaborator spoke the calibration remark and corrected speaker attribution';PATH='nodes/actual-later.txt'})
 $nodes.Add(@{ID=$current;TYPE='CURRENT';PERSON_ID=$person;RELATION_ID=$relation;PROJECT_ID=$project;TIME='2026-03-04';STATE='CURRENT';AUTHORITY='VERIFIED';SPEAKER_ID=$person;SOURCE_ID=$actual;SUMMARY='current unfinished work is bounded semantic relationship retrieval for local continuity';PATH='nodes/current.txt'})
 $nodes.Add(@{ID=$learning;TYPE='LEARNING';PERSON_ID=$person;RELATION_ID=$relation;PROJECT_ID=$project;TIME='2026-03-03';STATE='VERIFIED';AUTHORITY='VERIFIED';SPEAKER_ID=$person;SOURCE_ID=$actual;SUMMARY='verified learning says speaker identity requires source evidence before a memory correction is retained';PATH='nodes/learning.txt'})
 $nodes.Add(@{ID=(Token $seed 'candidate' 0);TYPE='CURRENT';PERSON_ID=$person;RELATION_ID=$relation;PROJECT_ID=$project;TIME='2026-03-09';STATE='CANDIDATE';AUTHORITY='UNVERIFIED';SPEAKER_ID=$person;SOURCE_ID='NONE';SUMMARY='newer candidate claims the archive steward originally spoke the calibration remark and all work is complete';PATH='nodes/candidate-newer.txt'})
 $nodes.Add(@{ID=(Token $seed 'stale' 0);TYPE='CURRENT';PERSON_ID=$person;RELATION_ID=$relation;PROJECT_ID=$project;TIME='2026-02-20';STATE='HISTORICAL';AUTHORITY='NON_CURRENT';SPEAKER_ID=$person;SOURCE_ID='SRC-STALE';SUMMARY='highly salient old current says semantic relationship retrieval remains untouched and calibration belongs to steward';PATH='nodes/current-stale.txt'})
 $nodes.Add(@{ID=$speakerEvent;TYPE='EVENT';PERSON_ID=$person;RELATION_ID=$relation;PROJECT_ID=$project;TIME='2026-03-05';STATE='HISTORICAL';AUTHORITY='VERIFIED';SPEAKER_ID=$person;SOURCE_ID='SRC-SPEAKER';SUMMARY='archive steward explicitly said preserve unknowns instead of inventing missing relationship details';PATH='nodes/event-speaker.txt'})
 $nodes.Add(@{ID=(Token $seed 'event' 3);TYPE='EVENT';PERSON_ID=$decoy;RELATION_ID='DECOY-REL';PROJECT_ID='DECOY-PROJECT';TIME='2026-03-05';STATE='HISTORICAL';AUTHORITY='VERIFIED';SPEAKER_ID=$decoy;SOURCE_ID='SRC-SPEAKER-X';SUMMARY='archive engineer explicitly said preserve unknowns instead of inventing missing relationship details';PATH='nodes/event-speaker-decoy.txt'})
 $nodes.Add(@{ID=$incomplete;TYPE='EVENT';PERSON_ID=$person;RELATION_ID=$relation;PROJECT_ID=$project;TIME='2026-03-06';STATE='CANDIDATE';AUTHORITY='UNVERIFIED';SPEAKER_ID='UNKNOWN';SOURCE_ID='NONE';SUMMARY='an incomplete note suggests an unnamed speaker changed the relationship boundary';PATH='nodes/event-incomplete.txt'})
 for($i=0;$i-lt180;$i++){$p=if($i%7-eq0){$decoy}else{Token $seed 'noise-person' $i};$nodes.Add(@{ID=(Token $seed 'noise' $i);TYPE=if($i%3-eq0){'EVENT'}elseif($i%3-eq1){'LEARNING'}else{'CURRENT'};PERSON_ID=$p;RELATION_ID=(Token $seed 'noise-rel' $i);PROJECT_ID=(Token $seed 'noise-project' ($i%21));TIME=('2025-{0:D2}-{1:D2}'-f(($i%12)+1),(($i%27)+1));STATE=if($i%4-eq0){'CANDIDATE'}else{'HISTORICAL'};AUTHORITY=if($i%4-eq0){'UNVERIFIED'}else{'NON_CURRENT'};SPEAKER_ID=$p;SOURCE_ID=(Token $seed 'noise-source' $i);SUMMARY="archive continuity event $i discusses calibration relationships current learning and speaker evidence in another synthetic project";PATH=("nodes/noise-{0:D3}.txt"-f$i)})}
 $catalog=[Collections.Generic.List[string]]::new();$personIndex=[Collections.Generic.List[string]]::new();$eventShards=@{};foreach($name in @('calibration','operations','music','travel','game','research')){$eventShards[$name]=[Collections.Generic.List[string]]::new()};$noiseEvent=0
 foreach($n in $nodes){$n.PATH='nodes/by-id/'+$n.ID+'.txt';Add-Node $catalog $n;if($n.TYPE -eq 'PERSON'){Add-Node $personIndex $n};if($n.TYPE -eq 'EVENT'){if($n.ID -in @($historical,$speakerEvent,$incomplete,(Token $seed 'event' 3))){Add-Node $eventShards['calibration'] $n}else{$bucket=@('operations','music','travel','game','research')[$noiseEvent%5];Add-Node $eventShards[$bucket] $n;$noiseEvent++}};$fileLines=[Collections.Generic.List[string]]::new();foreach($key in @('ID','TYPE','PERSON_ID','RELATION_ID','PROJECT_ID','TIME','STATE','AUTHORITY','SPEAKER_ID','SOURCE_ID','SUMMARY')){$fileLines.Add("$key=$($n[$key])")};if($n.ID -eq $person){$fileLines.Add("RELATIONSHIP_NODE_ID=$relation")};if($n.ID -eq $relation){$fileLines.Add("CURRENT_NODE_ID=$current")};if($n.ID -eq $current){$fileLines.Add("LEARNING_NODE_ID=$learning");$fileLines.Add("CURRENT_VALUE=$(Token $seed 'state-r2' 0)");$fileLines.Add("UNFINISHED_ITEM=$unfinished");$fileLines.Add("UNKNOWN=$unknown")};WriteText (Join-Path $brain $n.PATH) $fileLines}
 WriteText (Join-Path $brain 'archive\Full Node Catalog.txt') $catalog;WriteText (Join-Path $brain 'index\Person Candidates.txt') $personIndex;foreach($name in $eventShards.Keys){WriteText (Join-Path $brain "index\events-$name.txt") $eventShards[$name]};$eventDirectory=[Collections.Generic.List[string]]::new();Add-Region $eventDirectory 'CALIBRATION' 'speaker attribution relationship correction unknown evidence and calibration history' 'index/events-calibration.txt';Add-Region $eventDirectory 'OPERATIONS' 'unrelated operational schedules facilities and equipment events' 'index/events-operations.txt';Add-Region $eventDirectory 'MUSIC' 'unrelated music recording song arrangement and performance events' 'index/events-music.txt';Add-Region $eventDirectory 'TRAVEL' 'unrelated travel route vehicle weather and lodging events' 'index/events-travel.txt';Add-Region $eventDirectory 'GAME' 'unrelated game progress save state quest and item events' 'index/events-game.txt';Add-Region $eventDirectory 'RESEARCH' 'unrelated research papers experiments and measurement events' 'index/events-research.txt';WriteText (Join-Path $brain 'index\Event Region Directory.txt') $eventDirectory;WriteText (Join-Path $brain 'index\Region Index.txt') @('CONTINUITY_REGION=index/Person Candidates.txt','SPEAKER_DIRECTORY=index/Event Region Directory.txt','INCOMPLETE_DIRECTORY=index/Event Region Directory.txt','UNKNOWN_POLICY=ASK')
 WriteText (Join-Path $brain 'boot\Brain Entry.txt') @('REGION_INDEX=index/Region Index.txt','RETRIEVAL=HIERARCHICAL_SEMANTIC_RELATIONAL','NODE_ADDRESS=nodes/by-id/{ID}.txt','AUTHORITY_GATE=DETERMINISTIC','BOOT_CONTRACT=V08')
 WriteText (Join-Path $root 'tasks\continuity.txt') @('After the archive steward and trusted collaborator corrected who spoke during calibration, what verified lesson guides the unfinished local continuity work now?')
 WriteText (Join-Path $root 'tasks\speaker.txt') @('Who did the archive steward record as saying that missing relationship details must stay unknown instead of being invented?')
 WriteText (Join-Path $root 'tasks\incomplete.txt') @('Did the unnamed speaker definitely change the relationship boundary?')
 WriteText (Join-Path $root 'tasks\unknown.txt') @('What is the verified current state of the lunar orchard beacon?')
 WriteText (Join-Path $oracle 'Expected.txt') @("PERSON_ID=$person","RELATIONSHIP_ID=$relation","HISTORICAL_ID=$historical","ACTUAL_ID=$actual","CURRENT_ID=$current","LEARNING_ID=$learning","SPEAKER_EVENT_ID=$speakerEvent","SPEAKER_ID=$person","CURRENT_VALUE=$(Token $seed 'state-r2' 0)","UNFINISHED_ITEM=$unfinished","UNKNOWN=$unknown")
 $brainBytes=(Get-ChildItem -LiteralPath $brain -Recurse -File|Measure-Object Length -Sum).Sum;WriteText (Join-Path $root 'Build Evidence.txt') @("NODE_COUNT=$($nodes.Count)","BRAIN_BYTES=$brainBytes",'GLOBAL_CATALOG_RUNTIME_ACCESS=DENIED','BOOT_CONTRACT=V08')
}
function Run-Child([string]$root,[int]$seed){$pwsh=(Get-Process -Id $PID).Path;$q={param($s)"'"+([string]$s).Replace("'","''")+"'"};$cmd="& $(& $q $PSCommandPath) -Mode Boot -RunRoot $(& $q $root) -Seed $seed -Core $(& $q $Core) -EmbeddingModel $(& $q $EmbeddingModel)";$enc=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($cmd));$out=Join-Path $root 'evidence\boot.stdout.txt';$err=Join-Path $root 'evidence\boot.stderr.txt';$null=New-Item -ItemType Directory -Force -Path (Split-Path $out);$p=Start-Process $pwsh -ArgumentList @('-NoProfile','-EncodedCommand',$enc) -Wait -PassThru -WindowStyle Hidden -RedirectStandardOutput $out -RedirectStandardError $err;[pscustomobject]@{ExitCode=$p.ExitCode}}

if($Mode -eq 'Boot'){
 $brain=Join-Path $RunRoot 'brain'
 $entry=ReadText (Join-Path $brain 'boot\Brain Entry.txt')
 $regionPath=Field $entry 'REGION_INDEX'
 $region=ReadText (Join-Path $brain $regionPath)
 $build=ReadText (Join-Path $RunRoot 'Build Evidence.txt')
 $brainBytes=Field $build 'BRAIN_BYTES';$nodeCount=Field $build 'NODE_COUNT';$lines=[Collections.Generic.List[string]]::new()
 foreach($taskName in @('continuity','speaker','incomplete','unknown')){
  $task=ReadText (Join-Path $RunRoot ("tasks\$taskName.txt"));$sw=[Diagnostics.Stopwatch]::StartNew();$intent=Core $task;$intentValue=Field $intent.Text 'INTENT'
  $loaded=[Collections.Generic.List[object]]::new();$readPaths=[Collections.Generic.List[string]]::new();$readPaths.Add('boot/Brain Entry.txt');$readPaths.Add($regionPath)
  $candidateCount=0;$regionCandidateCount=0;$topScore=0.0;$margin=0.0;$regionTopScore=0.0;$regionMargin=0.0;$embeddingCalls=0;$embeddingMs=0;$candidateIndex='';$directoryText='';$decision='ASK';$candidatePath=$null
  if($intentValue -eq 'CONTINUITY'){$candidatePath=Field $region 'CONTINUITY_REGION'}
  elseif($intentValue -in @('SPEAKER','INCOMPLETE')){
   $directoryKey=if($intentValue -eq 'SPEAKER'){'SPEAKER_DIRECTORY'}else{'INCOMPLETE_DIRECTORY'};$directoryPath=Field $region $directoryKey;$directoryText=ReadText (Join-Path $brain $directoryPath);$readPaths.Add($directoryPath);$regions=Parse-Index $directoryText;$regionCandidateCount=$regions.Count
   $regionEmbeddings=Embed @($regions|ForEach-Object{$_.SUMMARY});$regionQuery=Embed @($task);$embeddingCalls+=2;$embeddingMs+=$regionEmbeddings.Ms+$regionQuery.Ms;$regionScored=for($i=0;$i-lt$regions.Count;$i++){[pscustomobject]@{R=$regions[$i];Score=Cosine $regionQuery.Vectors[0] $regionEmbeddings.Vectors[$i]}};$regionRank=@($regionScored|Sort-Object Score -Descending);if($regionRank.Count-ge1){$regionTopScore=$regionRank[0].Score};if($regionRank.Count-ge2){$regionMargin=$regionRank[0].Score-$regionRank[1].Score}else{$regionMargin=1.0};if($regionRank.Count-ge1 -and $regionTopScore-ge0.32 -and $regionMargin-ge0.005){$candidatePath=$regionRank[0].R.PATH}
  }
  if($candidatePath){
   $candidateIndex=ReadText (Join-Path $brain $candidatePath);$readPaths.Add($candidatePath);$candidates=Parse-Index $candidateIndex;$candidateCount=$candidates.Count;$candidateEmbeddings=Embed @($candidates|ForEach-Object{$_.SUMMARY});$queryEmbedding=Embed @($task);$embeddingCalls+=2;$embeddingMs+=$candidateEmbeddings.Ms+$queryEmbedding.Ms;$scored=for($i=0;$i-lt$candidates.Count;$i++){[pscustomobject]@{R=$candidates[$i];Score=Cosine $queryEmbedding.Vectors[0] $candidateEmbeddings.Vectors[$i]}};$rank=@($scored|Sort-Object Score -Descending);if($rank.Count-ge1){$topScore=$rank[0].Score};if($rank.Count-ge2){$margin=$rank[0].Score-$rank[1].Score}else{$margin=1.0}
   if($intentValue -eq 'CONTINUITY'){
    if($rank.Count-lt1 -or $topScore-lt0.45 -or $margin-lt0.015){$decision='ASK'}else{$person=Read-Node $brain $rank[0].R.ID;$loaded.Add($person);if($person.STATE-ne'CURRENT' -or $person.AUTHORITY-ne'VERIFIED'){$decision='HOLD'}else{$relationship=Read-Node $brain $person.RELATIONSHIP_NODE_ID;$loaded.Add($relationship);$current=Read-Node $brain $relationship.CURRENT_NODE_ID;$loaded.Add($current);$actual=Read-Node $brain $current.SOURCE_ID;$loaded.Add($actual);$historical=Read-Node $brain $actual.SOURCE_ID;$loaded.Add($historical);$learning=Read-Node $brain $current.LEARNING_NODE_ID;$loaded.Add($learning);$valid=$relationship.PERSON_ID-eq$person.PERSON_ID -and $relationship.STATE-eq'CURRENT' -and $relationship.AUTHORITY-eq'VERIFIED' -and $current.STATE-eq'CURRENT' -and $current.AUTHORITY-eq'VERIFIED' -and $actual.STATE-eq'ACTUAL' -and $actual.AUTHORITY-eq'VERIFIED' -and $historical.STATE-eq'HISTORICAL' -and $historical.AUTHORITY-eq'VERIFIED' -and $learning.STATE-eq'VERIFIED' -and $learning.AUTHORITY-eq'VERIFIED';$decision=if($valid){'GO'}else{'HOLD'}}}
   }elseif($intentValue -eq 'SPEAKER'){
    if($rank.Count-lt1 -or $topScore-lt0.45 -or $margin-lt0.01){$decision='ASK'}else{$event=Read-Node $brain $rank[0].R.ID;$loaded.Add($event);$decision=if($event.TYPE-eq'EVENT' -and $event.STATE-eq'HISTORICAL' -and $event.AUTHORITY-eq'VERIFIED' -and $event.SPEAKER_ID-ne'UNKNOWN'){'GO'}else{'HOLD'}}
   }elseif($intentValue -eq 'INCOMPLETE'){
    if($rank.Count-lt1 -or $topScore-lt0.40){$decision='ASK'}else{$event=Read-Node $brain $rank[0].R.ID;$loaded.Add($event);$decision=if($event.AUTHORITY-ne'VERIFIED' -or $event.SPEAKER_ID-eq'UNKNOWN' -or $event.SOURCE_ID-eq'NONE'){'HOLD'}else{'ASK'}}
   }
  }
  foreach($n in $loaded){$readPaths.Add($n.PATH)}
  $loadedBytes=[int](($loaded|ForEach-Object{[Text.Encoding]::UTF8.GetByteCount($_.TEXT)}|Measure-Object -Sum).Sum);$working=[Text.Encoding]::UTF8.GetByteCount($entry)+[Text.Encoding]::UTF8.GetByteCount($region)+[Text.Encoding]::UTF8.GetByteCount($directoryText)+[Text.Encoding]::UTF8.GetByteCount($candidateIndex)+$loadedBytes;$sw.Stop()
  $lines.Add("[$taskName]");$lines.Add("INTENT=$intentValue");$lines.Add("DECISION=$decision");$lines.Add("REGION_CANDIDATE_COUNT=$regionCandidateCount");$lines.Add("REGION_TOP_SCORE=$([math]::Round($regionTopScore,4))");$lines.Add("REGION_MARGIN=$([math]::Round($regionMargin,4))");$lines.Add("CANDIDATE_COUNT=$candidateCount");$lines.Add("TOP_SCORE=$([math]::Round($topScore,4))");$lines.Add("MARGIN=$([math]::Round($margin,4))");$lines.Add("LOADED_NODES=$($loaded.Count)");$lines.Add("WORKING_SET_BYTES=$working");$lines.Add("INPUT_TOKENS=$($intent.Prompt)");$lines.Add("OUTPUT_TOKENS=$($intent.Output)");$lines.Add('MODEL_CALLS=1');$lines.Add("EMBEDDING_CALLS=$embeddingCalls");$lines.Add("EMBEDDING_MS=$embeddingMs");$lines.Add("LATENCY_MS=$($sw.ElapsedMilliseconds)");$lines.Add("LOADED_IDS=$(($loaded|ForEach-Object{$_.ID})-join';')");$lines.Add("READ_PATHS=$($readPaths-join';')");$lines.Add('GLOBAL_CATALOG_LOADED=False');$lines.Add('')
 }
 $lines.Insert(0,'BRAIN_BYTES='+$brainBytes);$lines.Insert(0,'REGION_INDEX_BYTES='+[Text.Encoding]::UTF8.GetByteCount($region));$lines.Insert(0,'NODE_COUNT='+$nodeCount);WriteText (Join-Path $RunRoot 'evidence\Retrieval Result.txt') $lines;exit 0
}

if($Mode -eq 'Boot-Legacy'){
 $brain=Join-Path $RunRoot 'brain';$entry=ReadText (Join-Path $brain 'boot\Brain Entry.txt');$regionPath=Field $entry 'REGION_INDEX';$region=ReadText (Join-Path $brain $regionPath);$build=ReadText (Join-Path $RunRoot 'Build Evidence.txt');$brainBytes=Field $build 'BRAIN_BYTES';$nodeCount=Field $build 'NODE_COUNT';$lines=[Collections.Generic.List[string]]::new()
 foreach($taskName in @('continuity','speaker','incomplete','unknown')){
  $task=ReadText (Join-Path $RunRoot ("tasks\$taskName.txt"));$sw=[Diagnostics.Stopwatch]::StartNew();$intent=Core $task;$intentValue=Field $intent.Text 'INTENT';$regionKey=if($intentValue -eq 'CONTINUITY'){'CONTINUITY_REGION'}elseif($intentValue -eq 'SPEAKER'){'SPEAKER_REGION'}elseif($intentValue -eq 'INCOMPLETE'){'INCOMPLETE_REGION'}else{$null};$loaded=[Collections.Generic.List[object]]::new();$candidateCount=0;$topScore=0.0;$margin=0.0;$embeddingCalls=0;$embeddingMs=0;$candidateIndex='';$decision='ASK'
  if($regionKey){$candidatePath=Field $region $regionKey;$candidateIndex=ReadText (Join-Path $brain $candidatePath);$candidates=Parse-Index $candidateIndex;$candidateCount=$candidates.Count;$summaries=@($candidates|ForEach-Object{$_.SUMMARY});$candidateEmbeddings=Embed $summaries;$queryEmbedding=Embed @($task);$embeddingCalls=2;$embeddingMs=$candidateEmbeddings.Ms+$queryEmbedding.Ms;$scored=for($i=0;$i -lt $candidates.Count;$i++){[pscustomobject]@{R=$candidates[$i];Score=Cosine $queryEmbedding.Vectors[0] $candidateEmbeddings.Vectors[$i]}};$rank=@($scored|Sort-Object Score -Descending);if($rank.Count -ge 1){$topScore=$rank[0].Score};if($rank.Count -ge 2){$margin=$rank[0].Score-$rank[1].Score}else{$margin=1.0}
   if($intentValue -eq 'CONTINUITY'){
    if($rank.Count -lt 1 -or $topScore -lt 0.45 -or $margin -lt 0.015){$decision='ASK'}else{$person=Read-Node $brain $rank[0].R.ID;$loaded.Add($person);if($person.STATE -ne 'CURRENT' -or $person.AUTHORITY -ne 'VERIFIED'){$decision='HOLD'}else{$relationship=Read-Node $brain $person.RELATIONSHIP_NODE_ID;$loaded.Add($relationship);$current=Read-Node $brain $relationship.CURRENT_NODE_ID;$loaded.Add($current);$actual=Read-Node $brain $current.SOURCE_ID;$loaded.Add($actual);$historical=Read-Node $brain $actual.SOURCE_ID;$loaded.Add($historical);$learning=Read-Node $brain $current.LEARNING_NODE_ID;$loaded.Add($learning);$valid=$relationship.PERSON_ID -eq $person.PERSON_ID -and $relationship.STATE -eq 'CURRENT' -and $relationship.AUTHORITY -eq 'VERIFIED' -and $current.STATE -eq 'CURRENT' -and $current.AUTHORITY -eq 'VERIFIED' -and $actual.STATE -eq 'ACTUAL' -and $actual.AUTHORITY -eq 'VERIFIED' -and $historical.STATE -eq 'HISTORICAL' -and $historical.AUTHORITY -eq 'VERIFIED' -and $learning.STATE -eq 'VERIFIED' -and $learning.AUTHORITY -eq 'VERIFIED';$decision=if($valid){'GO'}else{'HOLD'}}}
   }
   elseif($intentValue -eq 'SPEAKER'){if($rank.Count -lt 1 -or $topScore -lt 0.45 -or $margin -lt 0.01){$decision='ASK'}else{$event=Read-Node $brain $rank[0].R.ID;$loaded.Add($event);$decision=if($event.TYPE -eq 'EVENT' -and $event.STATE -eq 'HISTORICAL' -and $event.AUTHORITY -eq 'VERIFIED' -and $event.SPEAKER_ID -ne 'UNKNOWN'){'GO'}else{'HOLD'}}}
   elseif($intentValue -eq 'INCOMPLETE'){if($rank.Count -lt 1){$decision='ASK'}else{$event=Read-Node $brain $rank[0].R.ID;$loaded.Add($event);$decision=if($event.AUTHORITY -ne 'VERIFIED' -or $event.SPEAKER_ID -eq 'UNKNOWN' -or $event.SOURCE_ID -eq 'NONE'){'HOLD'}else{'ASK'}}}
  }
  $loadedBytes=($loaded|ForEach-Object{[Text.Encoding]::UTF8.GetByteCount($_.TEXT)}|Measure-Object -Sum).Sum;$working=[Text.Encoding]::UTF8.GetByteCount($entry)+[Text.Encoding]::UTF8.GetByteCount($region)+[Text.Encoding]::UTF8.GetByteCount($candidateIndex)+$loadedBytes;$sw.Stop();$lines.Add("[$taskName]");$lines.Add("INTENT=$intentValue");$lines.Add("DECISION=$decision");$lines.Add("CANDIDATE_COUNT=$candidateCount");$lines.Add("TOP_SCORE=$([math]::Round($topScore,4))");$lines.Add("MARGIN=$([math]::Round($margin,4))");$lines.Add("LOADED_NODES=$($loaded.Count)");$lines.Add("WORKING_SET_BYTES=$working");$lines.Add("INPUT_TOKENS=$($intent.Prompt)");$lines.Add("OUTPUT_TOKENS=$($intent.Output)");$lines.Add('MODEL_CALLS=1');$lines.Add("EMBEDDING_CALLS=$embeddingCalls");$lines.Add("EMBEDDING_MS=$embeddingMs");$lines.Add("LATENCY_MS=$($sw.ElapsedMilliseconds)");$lines.Add("LOADED_IDS=$(($loaded|ForEach-Object{$_.ID})-join';')");$lines.Add("READ_PATHS=boot/Brain Entry.txt;$regionPath;$(if($regionKey){Field $region $regionKey}else{'NONE'});$(($loaded|ForEach-Object{$_.PATH})-join';')");$lines.Add('GLOBAL_CATALOG_LOADED=False');$lines.Add('')
 }
 $lines.Insert(0,'BRAIN_BYTES='+$brainBytes);$lines.Insert(0,'REGION_INDEX_BYTES='+[Text.Encoding]::UTF8.GetByteCount($region));$lines.Insert(0,'NODE_COUNT='+$nodeCount);WriteText (Join-Path $RunRoot 'evidence\Retrieval Result.txt') $lines;exit 0
}

if($Mode -eq 'Orchestrate'){$v6=Join-Path (Split-Path $scriptRoot -Parent) 'Model Brain Prototype v0.6';$v6r=Join-Path $v6 'results\latest-result.txt';if(-not(Test-Path $v6r) -or (Field (ReadText $v6r) 'GATE') -ne 'PASS_ONCE'){throw 'v0.6 baseline unavailable'};$null=New-Item -ItemType Directory -Force -Path (Join-Path $scriptRoot 'runs'),(Join-Path $scriptRoot 'results');$summary=[Collections.Generic.List[string]]::new();$summary.Add('Asteria v0.7 Result');$pass=$true
 foreach($s in @(701,1701,9701)){$run=Join-Path $scriptRoot "runs\seed-$s";if(Test-Path $run){Remove-Item $run -Recurse -Force};Build-Brain $run $s;$child=Run-Child $run $s;if($child.ExitCode -ne 0){$summary.Add("SEED_$s=FAIL");$pass=$false;break};$o=ReadText (Join-Path $run 'oracle\Expected.txt');$r=ReadText (Join-Path $run 'evidence\Retrieval Result.txt');$continuity=[regex]::Match($r,'(?ms)^\[continuity\](.*?)(?=^\[speaker\])').Groups[1].Value;$speaker=[regex]::Match($r,'(?ms)^\[speaker\](.*?)(?=^\[incomplete\])').Groups[1].Value;$incomplete=[regex]::Match($r,'(?ms)^\[incomplete\](.*?)(?=^\[unknown\])').Groups[1].Value;$unknownBlock=[regex]::Match($r,'(?ms)^\[unknown\](.*)$').Groups[1].Value;$ids=Field $continuity 'LOADED_IDS';$ok=(Field $continuity 'DECISION') -eq 'GO' -and $ids.Contains((Field $o 'RELATIONSHIP_ID')) -and $ids.Contains((Field $o 'HISTORICAL_ID')) -and $ids.Contains((Field $o 'ACTUAL_ID')) -and $ids.Contains((Field $o 'CURRENT_ID')) -and $ids.Contains((Field $o 'LEARNING_ID')) -and (Field $speaker 'DECISION') -eq 'GO' -and (Field $speaker 'LOADED_IDS') -eq (Field $o 'SPEAKER_EVENT_ID') -and (Field $incomplete 'DECISION') -eq 'HOLD' -and (Field $unknownBlock 'DECISION') -eq 'ASK';if($ok){$summary.Add("SEED_$s=PASS")}else{$summary.Add("SEED_$s=FAIL");$pass=$false;break}}
 $summary.Add('GATE_1_SEMANTIC_RELATIONAL='+$(if($pass){'PASS_ONCE'}else{'PARTIAL'}));$summary.Add('GATE_2_MULTI_EVENT='+$(if($pass){'PASS_ONCE'}else{'PARTIAL'}));$summary.Add('GATE='+$(if($pass){'PASS_ONCE'}else{'PARTIAL'}));WriteText (Join-Path $scriptRoot 'results\latest-result.txt') $summary;$summary;if(-not$pass){exit 2}else{exit 0}}
